version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=productdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    image: product-service:latest
    ports:
      - "8081:8081"
    networks:
      - backend-network
    volumes:
      - ./shared:/workspace/shared
      - ./services/product-service:/workspace/services/product-service
    environment:
      - AIR_DEBUG=true
      - CMD=local
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=productdb
      - SSL_MODE=disable
    depends_on:
      - db

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    image: order-service:latest
    ports:
      - "8082:8082"
    volumes:
      - ./shared:/workspace/shared
      - ./services/order-service:/workspace/services/order-service
    networks:
      - backend-network

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    image: api-gateway-service:latest
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/workspace/shared
      - ./services/api-gateway:/workspace/services/api-gateway
    depends_on:
      - product-service
      - order-service
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
